-- ════════════════════════════════════════════════════════════════════════════
--  FLC Check-In — full database initialisation
--
--  This is the single source of truth. Run it once on a fresh Supabase
--  project (paste into the SQL editor, or `supabase db push` if you have
--  the CLI wired up). It supersedes every prior schema/migration file.
--
--  Idempotent: every CREATE uses IF NOT EXISTS or CREATE OR REPLACE, so it's
--  safe to re-run on an already-initialised database without losing data.
--
--  What this sets up:
--    • Tables: member_profiles, checkin_events, checkin_records,
--              event_scope_members, checkin_attempts, checkin_devices,
--              face_match_claims, absence_notes, audit_log
--    • Helpers: point_in_polygon, haversine_meters, point_in_event_geofence
--    • RPCs:    create_checkin_event, reset_event_pin, record_pin_attempt,
--              claim_device_for_event, claim_face_match,
--              report_member_location, auto_checkout_expired_events,
--              submit_checkin
--    • Grants for the anon role used by the @supabase/supabase-js client
--
--  Design notes:
--    • RLS is OFF. All access goes through security-definer RPCs that
--      enforce auth themselves.
--    • Member IDs are TEXT (FLC graph uses MongoDB ObjectIds, not UUIDs).
--      Event IDs are UUID (generated by Postgres).
--    • PINs are rotating 6-digit OTPs derived from the event's qr_secret —
--      not stored hashes. The pin_hash/pin_set_at columns are kept for
--      back-compat but the rotating-PIN path doesn't use them.
-- ════════════════════════════════════════════════════════════════════════════


-- ─── Extensions ─────────────────────────────────────────────────────────────
-- pgcrypto lives in the `extensions` schema (Supabase convention) so the
-- security-definer RPCs resolve crypt()/gen_salt()/hmac() via search_path.
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;


-- ════════════════════════════════════════════════════════════════════════════
--  TABLES
-- ════════════════════════════════════════════════════════════════════════════

-- ─── member_profiles ────────────────────────────────────────────────────────
-- Local cache of leader identity. id is the FLC graph member id (24-char
-- MongoDB ObjectId hex string, stored as text). face_descriptor is a
-- 128-float vector from face-api.js used for Face ID check-in.
create table if not exists public.member_profiles (
  id                  text primary key,
  email               text,
  first_name          text,
  last_name           text,
  phone               text,
  roles               text[] not null default '{}',
  bacenta_id          text, bacenta_name      text,
  governorship_id     text, governorship_name text,
  council_id          text, council_name      text,
  stream_id           text, stream_name       text,
  campus_id           text, campus_name       text,
  oversight_id        text, oversight_name    text,
  denomination_id     text, denomination_name text,
  face_descriptor     double precision[],
  updated_at          timestamptz not null default now()
);

create index if not exists member_profiles_bacenta_idx      on public.member_profiles (bacenta_id);
create index if not exists member_profiles_governorship_idx on public.member_profiles (governorship_id);
create index if not exists member_profiles_council_idx      on public.member_profiles (council_id);
create index if not exists member_profiles_stream_idx       on public.member_profiles (stream_id);
create index if not exists member_profiles_campus_idx       on public.member_profiles (campus_id);
create index if not exists member_profiles_oversight_idx    on public.member_profiles (oversight_id);


-- ─── superadmins ────────────────────────────────────────────────────────────
-- Email allowlist for accounts that bypass the FLC member graph.
-- Managed via the Supabase dashboard Table Editor (no app UI needed).
create table if not exists public.superadmins (
  email       text primary key,
  note        text,
  created_at  timestamptz not null default now()
);
-- Direct SELECT intentionally NOT granted to anon.
-- Use the is_super_admin(p_email) RPC (defined in the GRANTS section below).


-- ─── checkin_events ─────────────────────────────────────────────────────────
create table if not exists public.checkin_events (
  id                          uuid primary key default gen_random_uuid(),
  name                        text not null,
  event_type                  text,
  status                      text not null default 'ACTIVE'
    check (status in ('ACTIVE', 'PAUSED', 'ENDED')),
  scope_level                 text not null
    check (scope_level in ('bacenta','governorship','council','stream','campus','oversight','denomination')),
  scope_church_id             text not null,
  scope_church_name           text not null,
  venue_name                  text,
  starts_at                   timestamptz not null,
  ends_at                     timestamptz not null,
  grace_period_min            int  not null default 15,
  auto_checkout_min           int  not null default 0,
  allowed_check_in_methods    text[] not null
    check (allowed_check_in_methods <@ array['QR','PIN','MANUAL','FACE_ID']),
  allowed_roles               text[] not null,
  geofence_type               text not null check (geofence_type in ('circle','polygon')),
  geofence_center_lat         double precision,
  geofence_center_lng         double precision,
  geofence_radius_m           int,
  geofence_polygon            jsonb,
  pin_hash                    text,
  pin_set_at                  timestamptz,
  qr_secret                   bytea not null,
  created_by_id               text not null references public.member_profiles(id),
  created_by_name             text,
  created_at                  timestamptz not null default now(),
  check (
    (geofence_type = 'circle'  and geofence_center_lat is not null and geofence_center_lng is not null and geofence_radius_m is not null)
    or
    (geofence_type = 'polygon' and geofence_polygon is not null)
  ),
  check (ends_at > starts_at)
);

create index if not exists checkin_events_status_ends_at_idx on public.checkin_events (status, ends_at);
create index if not exists checkin_events_scope_idx          on public.checkin_events (scope_level, scope_church_id);


-- ─── checkin_records ────────────────────────────────────────────────────────
create table if not exists public.checkin_records (
  id                  uuid primary key default gen_random_uuid(),
  event_id            uuid not null references public.checkin_events(id) on delete cascade,
  member_id           text not null references public.member_profiles(id),
  member_name         text,
  member_role         text,
  member_unit_name    text,
  checked_in_at       timestamptz not null default now(),
  checked_out_at      timestamptz,
  auto_checked_out    boolean not null default false,
  is_late             boolean not null default false,
  method              text not null check (method in ('QR','PIN','MANUAL','FACE_ID')),
  geo_verified        boolean not null,
  check_in_lat        double precision,
  check_in_lng        double precision,
  device_fingerprint  text not null,
  manual_reason       text,
  verified_by         text,
  unique (event_id, member_id)
);

create index if not exists checkin_records_event_idx  on public.checkin_records (event_id);
create index if not exists checkin_records_member_idx on public.checkin_records (member_id, checked_in_at desc);


-- ─── event_scope_members ────────────────────────────────────────────────────
-- Permanent snapshot: every member who was in-scope at event creation time,
-- keyed by their stable FLC graph ID (m.id from Neo4j — never changes even if
-- name / email / church unit changes). No FK to member_profiles so the row is
-- never dropped for members who haven't logged into the app yet.
create table if not exists public.event_scope_members (
  event_id    uuid  not null references public.checkin_events(id) on delete cascade,
  member_id   text  not null,   -- stable FLC graph ID (m.id)
  created_at  timestamptz not null default now(),
  primary key (event_id, member_id)
);

-- Fast lookup of all events a member was ever scoped to (History screen)
create index if not exists event_scope_members_member_idx
  on public.event_scope_members (member_id);


-- ─── checkin_attempts (PIN rate-limiting state, kept for back-compat) ───────
create table if not exists public.checkin_attempts (
  id              bigserial primary key,
  event_id        uuid not null references public.checkin_events(id) on delete cascade,
  member_id       text not null,
  attempted_at    timestamptz not null default now(),
  success         boolean not null,
  lockout_until   timestamptz
);

create index if not exists checkin_attempts_lookup_idx
  on public.checkin_attempts (event_id, member_id, attempted_at desc);


-- ─── checkin_devices (one device per member per event) ──────────────────────
create table if not exists public.checkin_devices (
  event_id            uuid not null references public.checkin_events(id) on delete cascade,
  device_fingerprint  text not null,
  member_id           text not null,
  first_seen_at       timestamptz not null default now(),
  primary key (event_id, device_fingerprint)
);


-- ─── face_match_claims (short-lived FACE_ID gate) ───────────────────────────
-- One row per (event, member). Inserted on local face match, deleted on
-- successful check-in. Stale rows (>60s) are ignored by submit_checkin.
create table if not exists public.face_match_claims (
  event_id   uuid not null,
  member_id  text not null,
  claimed_at timestamptz not null default now(),
  primary key (event_id, member_id)
);


-- ─── absence_notes (admin-recorded reasons for member absences) ──────────────
create table if not exists public.absence_notes (
  event_id    uuid        not null references public.checkin_events(id) on delete cascade,
  member_id   text        not null,
  reason      text        not null,
  recorded_by text        not null,
  recorded_at timestamptz not null default now(),
  primary key (event_id, member_id)
);


-- ─── audit_log (append-only admin action trail) ──────────────────────────────
create table if not exists public.audit_log (
  id          bigserial    primary key,
  action      text         not null,
  actor_id    text         not null,
  actor_name  text,
  event_id    uuid         references public.checkin_events(id) on delete set null,
  target_id   text,
  target_name text,
  details     jsonb,
  created_at  timestamptz  not null default now()
);

create index if not exists audit_log_event_idx on public.audit_log(event_id, created_at desc);


-- ─── RLS enabled with minimum-required policies ─────────────────────────────
-- checkin_attempts, checkin_devices, face_match_claims have no policy
-- (deny-all for direct access) — they are only written via security-definer RPCs.
alter table public.member_profiles   enable row level security;
alter table public.checkin_events    enable row level security;
alter table public.checkin_records   enable row level security;
alter table public.event_scope_members enable row level security;
alter table public.checkin_attempts  enable row level security;
alter table public.checkin_devices   enable row level security;
alter table public.face_match_claims enable row level security;
alter table public.superadmins       enable row level security;
alter table public.absence_notes     enable row level security;
alter table public.audit_log         enable row level security;

create policy "anon_all_member_profiles"       on public.member_profiles       for all to anon using (true) with check (true);
create policy "anon_all_checkin_events"        on public.checkin_events        for all to anon using (true) with check (true);
create policy "anon_all_checkin_records"       on public.checkin_records       for all to anon using (true) with check (true);
create policy "anon_all_event_scope_members"   on public.event_scope_members   for all to anon using (true) with check (true);
create policy "anon_all_absence_notes"         on public.absence_notes         for all to anon using (true) with check (true);
create policy "anon_insert_audit_log"          on public.audit_log             for insert to anon with check (true);
create policy "anon_read_audit_log"            on public.audit_log             for select to anon using (true);
-- superadmins: no policy → deny-all for direct access (RPC is the only read path).


-- ════════════════════════════════════════════════════════════════════════════
--  HELPERS (pure functions)
-- ════════════════════════════════════════════════════════════════════════════

-- Point-in-polygon via ray casting. Polygon is a jsonb array of [lat, lng].
create or replace function public.point_in_polygon(
  p_lat     double precision,
  p_lng     double precision,
  p_polygon jsonb
) returns boolean
language plpgsql
immutable
as $$
declare
  v_n int;
  v_inside boolean := false;
  v_i int := 0;
  v_j int;
  v_xi double precision; v_yi double precision;
  v_xj double precision; v_yj double precision;
begin
  v_n := jsonb_array_length(p_polygon);
  if v_n < 3 then return false; end if;
  v_j := v_n - 1;
  while v_i < v_n loop
    v_yi := (p_polygon -> v_i ->> 0)::double precision;
    v_xi := (p_polygon -> v_i ->> 1)::double precision;
    v_yj := (p_polygon -> v_j ->> 0)::double precision;
    v_xj := (p_polygon -> v_j ->> 1)::double precision;
    if ((v_yi > p_lat) <> (v_yj > p_lat))
       and (p_lng < (v_xj - v_xi) * (p_lat - v_yi) / nullif((v_yj - v_yi), 0) + v_xi) then
      v_inside := not v_inside;
    end if;
    v_j := v_i;
    v_i := v_i + 1;
  end loop;
  return v_inside;
end;
$$;

-- Great-circle distance in metres.
create or replace function public.haversine_meters(
  p_lat1 double precision, p_lng1 double precision,
  p_lat2 double precision, p_lng2 double precision
) returns double precision
language plpgsql
immutable
as $$
declare
  r constant double precision := 6371000;
  d_lat double precision;
  d_lng double precision;
  a double precision;
begin
  d_lat := radians(p_lat2 - p_lat1);
  d_lng := radians(p_lng2 - p_lng1);
  a := sin(d_lat / 2) ^ 2
     + cos(radians(p_lat1)) * cos(radians(p_lat2)) * sin(d_lng / 2) ^ 2;
  return r * 2 * atan2(sqrt(a), sqrt(1 - a));
end;
$$;

-- Geofence check: dispatches on circle vs polygon.
create or replace function public.point_in_event_geofence(
  p_event_id uuid,
  p_lat      double precision,
  p_lng      double precision
) returns boolean
language plpgsql
stable
as $$
declare
  v_event public.checkin_events%rowtype;
begin
  select * into v_event from public.checkin_events where id = p_event_id;
  if not found then return false; end if;
  if v_event.geofence_type = 'circle' then
    return public.haversine_meters(
      v_event.geofence_center_lat, v_event.geofence_center_lng, p_lat, p_lng
    ) <= v_event.geofence_radius_m;
  elsif v_event.geofence_type = 'polygon' then
    return public.point_in_polygon(p_lat, p_lng, v_event.geofence_polygon);
  end if;
  return false;
end;
$$;


-- ════════════════════════════════════════════════════════════════════════════
--  RPCs
--
--  All security definer, all use member_id text. Earlier versions of this
--  schema had uuid-member-id overloads; the consolidated init drops those
--  defensively below before recreating the canonical text-only signatures,
--  so a re-run cleans up any drift from past migrations.
-- ════════════════════════════════════════════════════════════════════════════

-- Drop any historical uuid-member-id overloads (no-op on a fresh DB).
drop function if exists public.record_pin_attempt(uuid, uuid, text);
drop function if exists public.claim_device_for_event(uuid, text, uuid);
drop function if exists public.claim_face_match(uuid, uuid);
drop function if exists public.report_member_location(uuid, uuid, double precision, double precision);
drop function if exists public.submit_checkin(uuid, uuid, text, text, text, text, double precision, double precision, text, text, text);
drop function if exists public.create_checkin_event(text, text, text, text, text, timestamptz, timestamptz, int, int, text[], text[], text, double precision, double precision, int, jsonb, text, text, uuid, text);
drop function if exists public.create_checkin_event(text, text, text, text, text, timestamptz, timestamptz, int, int, text[], text[], text, double precision, double precision, int, jsonb, text, text, text, text);


-- ─── record_pin_attempt: bcrypt PIN with rate limiting ──────────────────────
-- Kept for back-compat / direct callers; the rotating-PIN path in
-- submit_checkin does not use this.
create or replace function public.record_pin_attempt(
  p_event_id   uuid,
  p_member_id  text,
  p_pin_plain  text
) returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_event           public.checkin_events%rowtype;
  v_lockout_until   timestamptz;
  v_attempts_in_win int;
  v_attempts_left   int;
  v_match           boolean;
begin
  select * into v_event from public.checkin_events where id = p_event_id;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'event_not_found');
  end if;
  if v_event.status <> 'ACTIVE' then
    return jsonb_build_object('ok', false, 'reason', 'event_not_active', 'status', v_event.status);
  end if;
  if v_event.pin_hash is null then
    return jsonb_build_object('ok', false, 'reason', 'pin_not_set');
  end if;

  select max(lockout_until) into v_lockout_until
    from public.checkin_attempts
   where event_id = p_event_id
     and member_id = p_member_id
     and lockout_until is not null
     and lockout_until > now();
  if v_lockout_until is not null then
    return jsonb_build_object('ok', false, 'reason', 'locked_out', 'lockout_until', v_lockout_until);
  end if;

  v_match := (extensions.crypt(p_pin_plain, v_event.pin_hash) = v_event.pin_hash);

  if v_match then
    insert into public.checkin_attempts (event_id, member_id, success)
      values (p_event_id, p_member_id, true);
    return jsonb_build_object('ok', true);
  end if;

  select count(*) into v_attempts_in_win
    from public.checkin_attempts
   where event_id = p_event_id
     and member_id = p_member_id
     and success = false
     and attempted_at > now() - interval '10 minutes';

  if v_attempts_in_win + 1 >= 5 then
    insert into public.checkin_attempts (event_id, member_id, success, lockout_until)
      values (p_event_id, p_member_id, false, now() + interval '15 minutes');
    return jsonb_build_object('ok', false, 'reason', 'locked_out',
                              'lockout_until', now() + interval '15 minutes');
  end if;

  insert into public.checkin_attempts (event_id, member_id, success)
    values (p_event_id, p_member_id, false);
  v_attempts_left := 5 - (v_attempts_in_win + 1);
  return jsonb_build_object('ok', false, 'reason', 'wrong_pin', 'attempts_left', v_attempts_left);
end;
$$;


-- ─── claim_device_for_event: one device per member per event ────────────────
create or replace function public.claim_device_for_event(
  p_event_id     uuid,
  p_fingerprint  text,
  p_member_id    text
) returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_existing text;
begin
  insert into public.checkin_devices (event_id, device_fingerprint, member_id)
    values (p_event_id, p_fingerprint, p_member_id)
    on conflict (event_id, device_fingerprint) do nothing;

  select member_id into v_existing
    from public.checkin_devices
   where event_id = p_event_id and device_fingerprint = p_fingerprint;

  return v_existing = p_member_id;
end;
$$;


-- ─── claim_face_match: short-lived FACE_ID gate ─────────────────────────────
create or replace function public.claim_face_match(
  p_event_id  uuid,
  p_member_id text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.face_match_claims (event_id, member_id, claimed_at)
  values (p_event_id, p_member_id, now())
  on conflict (event_id, member_id)
    do update set claimed_at = now();
  return jsonb_build_object('ok', true);
exception
  when others then
    return jsonb_build_object('ok', false, 'reason', 'server_error', 'detail', sqlerrm);
end;
$$;


-- ─── report_member_location: location heartbeat + auto-checkout ─────────────
create or replace function public.report_member_location(
  p_event_id  uuid,
  p_member_id text,
  p_lat       double precision,
  p_lng       double precision
) returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_inside boolean;
  v_was_checked_out boolean := false;
begin
  v_inside := public.point_in_event_geofence(p_event_id, p_lat, p_lng);
  if not v_inside then
    update public.checkin_records
       set checked_out_at  = now(),
           auto_checked_out = true
     where event_id = p_event_id
       and member_id = p_member_id
       and checked_out_at is null;
    if found then v_was_checked_out := true; end if;
  end if;
  return jsonb_build_object('inside_fence', v_inside, 'checked_out', v_was_checked_out);
end;
$$;


-- ─── auto_checkout_expired_events: cron job for ended events ────────────────
create or replace function public.auto_checkout_expired_events()
returns int
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_count int := 0;
begin
  with closed as (
    update public.checkin_records cr
       set checked_out_at  = now(),
           auto_checked_out = true
      from public.checkin_events ce
     where cr.event_id = ce.id
       and ce.status = 'ACTIVE'
       and ce.ends_at <= now()
       and cr.checked_out_at is null
    returning cr.id
  )
  select count(*) into v_count from closed;

  update public.checkin_events
     set status = 'ENDED'
   where status = 'ACTIVE'
     and ends_at <= now();

  return v_count;
end;
$$;


-- ─── create_checkin_event: hashes the optional PIN server-side ──────────────
create or replace function public.create_checkin_event(
  p_name                     text,
  p_event_type               text,
  p_scope_level              text,
  p_scope_church_id          text,
  p_scope_church_name        text,
  p_venue_name               text,
  p_starts_at                timestamptz,
  p_ends_at                  timestamptz,
  p_grace_period_min         int,
  p_auto_checkout_min        int,
  p_allowed_check_in_methods text[],
  p_allowed_roles            text[],
  p_geofence_type            text,
  p_geofence_center_lat      double precision,
  p_geofence_center_lng      double precision,
  p_geofence_radius_m        int,
  p_geofence_polygon         jsonb,
  p_pin_plain                text,
  p_qr_secret_hex            text,
  p_created_by_id            text,
  p_created_by_name          text
) returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_id uuid;
  v_pin_hash text := null;
begin
  if p_pin_plain is not null then
    v_pin_hash := extensions.crypt(p_pin_plain, extensions.gen_salt('bf', 10));
  end if;

  insert into public.checkin_events (
    name, event_type, scope_level, scope_church_id, scope_church_name, venue_name,
    starts_at, ends_at, grace_period_min, auto_checkout_min,
    allowed_check_in_methods, allowed_roles,
    geofence_type, geofence_center_lat, geofence_center_lng, geofence_radius_m, geofence_polygon,
    pin_hash, pin_set_at, qr_secret,
    created_by_id, created_by_name
  ) values (
    p_name, p_event_type, p_scope_level, p_scope_church_id, p_scope_church_name, p_venue_name,
    p_starts_at, p_ends_at, p_grace_period_min, p_auto_checkout_min,
    p_allowed_check_in_methods, p_allowed_roles,
    p_geofence_type, p_geofence_center_lat, p_geofence_center_lng, p_geofence_radius_m, p_geofence_polygon,
    v_pin_hash, case when p_pin_plain is not null then now() else null end, decode(p_qr_secret_hex, 'hex'),
    p_created_by_id, p_created_by_name
  ) returning id into v_id;

  return v_id;
end;
$$;


-- ─── reset_event_pin: re-hash a new PIN and clear lockouts ──────────────────
create or replace function public.reset_event_pin(
  p_event_id uuid,
  p_pin_plain text
) returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  update public.checkin_events
     set pin_hash   = extensions.crypt(p_pin_plain, extensions.gen_salt('bf', 10)),
         pin_set_at = now()
   where id = p_event_id;

  update public.checkin_attempts
     set lockout_until = null
   where event_id = p_event_id
     and lockout_until is not null
     and lockout_until > now();
end;
$$;


-- ─── submit_checkin: single entry point for QR / PIN / FACE_ID / MANUAL ─────
-- All validation is performed atomically inside this function. PIN uses a
-- rotating 6-digit OTP derived from qr_secret (15s window, current or
-- previous bucket accepted). QR uses HMAC over 'eventId:bucket' (60s window).
-- FACE_ID requires a fresh face_match_claim (<60s) and consumes it.
create or replace function public.submit_checkin(
  p_event_id     uuid,
  p_member_id    text,
  p_member_name  text,
  p_member_role  text,
  p_member_unit  text,
  p_method       text,
  p_lat          double precision,
  p_lng          double precision,
  p_fingerprint  text,
  p_qr_token     text default null,
  p_pin_plain    text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_event          public.checkin_events%rowtype;
  v_now            timestamptz := now();
  v_qr_bucket_now  bigint;
  v_pin_bucket_now bigint;
  v_parts          text[];
  v_token_event_id text;
  v_token_bucket   bigint;
  v_token_sig_hex  text;
  v_expected_sig   bytea;
  v_otp_hmac       bytea;
  v_otp_int        bigint;
  v_otp_cur        text;
  v_otp_prev       text;
  v_in_fence       boolean;
  v_device_ok      boolean;
  v_is_late        boolean;
  v_record_id      uuid;
  v_claim_age      interval;
begin
  -- 1. Fetch event
  select * into v_event from public.checkin_events where id = p_event_id;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'event_not_found');
  end if;

  -- 2. Status and time window
  --    Check-in opens 1 hour before starts_at and closes at ends_at.
  if v_event.status = 'PAUSED' then
    return jsonb_build_object('ok', false, 'reason', 'event_paused');
  end if;
  if v_event.status = 'ENDED' then
    return jsonb_build_object('ok', false, 'reason', 'event_ended');
  end if;
  if v_now < (v_event.starts_at - interval '1 hour') then
    return jsonb_build_object(
      'ok',         false,
      'reason',     'not_started',
      'opens_at',   (v_event.starts_at - interval '1 hour')
    );
  end if;
  if v_now > v_event.ends_at then
    return jsonb_build_object('ok', false, 'reason', 'event_ended');
  end if;

  -- 3. Method allowed
  if not (p_method = any(v_event.allowed_check_in_methods)) then
    return jsonb_build_object('ok', false, 'reason', 'method_not_allowed');
  end if;

  -- 4. Method-specific verification
  if p_method = 'QR' then
    if p_qr_token is null then
      return jsonb_build_object('ok', false, 'reason', 'missing_qr_token');
    end if;

    v_parts := string_to_array(p_qr_token, ':');
    if array_length(v_parts, 1) <> 3 then
      return jsonb_build_object('ok', false, 'reason', 'invalid_qr_token');
    end if;

    v_token_event_id := v_parts[1];
    v_token_bucket   := v_parts[2]::bigint;
    v_token_sig_hex  := lower(v_parts[3]);

    if v_token_event_id <> p_event_id::text then
      return jsonb_build_object('ok', false, 'reason', 'invalid_qr_token');
    end if;

    v_qr_bucket_now := floor(extract(epoch from v_now) / 60)::bigint;
    if v_token_bucket <> v_qr_bucket_now and v_token_bucket <> (v_qr_bucket_now - 1) then
      return jsonb_build_object('ok', false, 'reason', 'qr_expired');
    end if;

    v_expected_sig := extensions.hmac(
      convert_to(v_token_event_id || ':' || v_token_bucket::text, 'UTF8'),
      v_event.qr_secret,
      'sha256'
    );
    if encode(v_expected_sig, 'hex') <> v_token_sig_hex then
      return jsonb_build_object('ok', false, 'reason', 'invalid_qr_token');
    end if;

  elsif p_method = 'PIN' then
    if p_pin_plain is null then
      return jsonb_build_object('ok', false, 'reason', 'missing_pin');
    end if;

    v_pin_bucket_now := floor(extract(epoch from v_now) / 15)::bigint;

    v_otp_hmac := extensions.hmac(
      convert_to(p_event_id::text || ':' || v_pin_bucket_now::text, 'UTF8'),
      v_event.qr_secret, 'sha256'
    );
    v_otp_int := (('x' || right(encode(v_otp_hmac, 'hex'), 8))::bit(32)::int4::bigint
                  + 4294967296) % 4294967296 % 1000000;
    v_otp_cur := lpad(v_otp_int::text, 6, '0');

    v_otp_hmac := extensions.hmac(
      convert_to(p_event_id::text || ':' || (v_pin_bucket_now - 1)::text, 'UTF8'),
      v_event.qr_secret, 'sha256'
    );
    v_otp_int := (('x' || right(encode(v_otp_hmac, 'hex'), 8))::bit(32)::int4::bigint
                  + 4294967296) % 4294967296 % 1000000;
    v_otp_prev := lpad(v_otp_int::text, 6, '0');

    if p_pin_plain <> v_otp_cur and p_pin_plain <> v_otp_prev then
      return jsonb_build_object('ok', false, 'reason', 'wrong_pin');
    end if;

  elsif p_method = 'FACE_ID' then
    -- Require a fresh claim (<60s). Consume it whether or not the rest of
    -- the check-in succeeds (the client must call claim_face_match again
    -- to retry).
    select v_now - claimed_at into v_claim_age
      from public.face_match_claims
     where event_id = p_event_id and member_id = p_member_id;

    if v_claim_age is null then
      return jsonb_build_object('ok', false, 'reason', 'face_match_required');
    end if;

    if v_claim_age > interval '60 seconds' then
      delete from public.face_match_claims
       where event_id = p_event_id and member_id = p_member_id;
      return jsonb_build_object('ok', false, 'reason', 'face_match_expired');
    end if;

    delete from public.face_match_claims
     where event_id = p_event_id and member_id = p_member_id;

  else
    -- MANUAL goes through submit_manual_check_in (direct insert by admin) — never
    -- through this RPC. Any other method is unknown.
    return jsonb_build_object('ok', false, 'reason', 'unsupported_method');
  end if;

  -- 5. Geofence
  v_in_fence := public.point_in_event_geofence(p_event_id, p_lat, p_lng);
  if not v_in_fence then
    return jsonb_build_object('ok', false, 'reason', 'outside_fence');
  end if;

  -- 6. Device fingerprint claim — skipped for MANUAL (admin shared kiosk).
  if p_method <> 'MANUAL' then
    v_device_ok := public.claim_device_for_event(p_event_id, p_fingerprint, p_member_id);
    if not v_device_ok then
      return jsonb_build_object('ok', false, 'reason', 'device_already_used');
    end if;
  end if;

  -- 7. Late detection — relative to starts_at, not the early window.
  --    Someone checking in before starts_at is never late.
  v_is_late := v_now > (v_event.starts_at + (v_event.grace_period_min * interval '1 minute'));

  -- 8. Insert record
  insert into public.checkin_records (
    event_id, member_id, member_name, member_role, member_unit_name,
    method, geo_verified, check_in_lat, check_in_lng,
    device_fingerprint, is_late
  ) values (
    p_event_id, p_member_id, p_member_name, p_member_role, p_member_unit,
    p_method, true, p_lat, p_lng, p_fingerprint, v_is_late
  )
  returning id into v_record_id;

  return jsonb_build_object(
    'ok', true,
    'record', jsonb_build_object(
      'id',      v_record_id,
      'is_late', v_is_late,
      'method',  p_method
    )
  );

exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'reason', 'already_checked_in');
  when others then
    return jsonb_build_object('ok', false, 'reason', 'server_error', 'detail', sqlerrm);
end;
$$;


-- ─── is_super_admin(p_email) ─────────────────────────────────────────────────
-- Security-definer: runs as postgres so it can read the superadmins table
-- even though anon has no direct SELECT on it. search_path pinned to prevent
-- search-path injection.
create or replace function public.is_super_admin(p_email text)
  returns boolean
  language plpgsql
  security definer
  set search_path = public, extensions
as $$
begin
  return exists (
    select 1 from public.superadmins
    where email = lower(trim(p_email))
  );
end;
$$;


-- ════════════════════════════════════════════════════════════════════════════
--  GRANTS
--  RLS is ON with permissive policies for tables the client accesses directly.
--  Tables accessed only via security-definer RPCs have no policy (deny-all).
-- ════════════════════════════════════════════════════════════════════════════

grant usage on schema public to anon;

grant select, insert, update, delete on
  public.member_profiles,
  public.checkin_events,
  public.checkin_records,
  public.event_scope_members,
  public.absence_notes
  to anon;
grant select, insert on public.audit_log to anon;
-- checkin_attempts, checkin_devices, face_match_claims: no direct grant
-- (security-definer RPCs run as postgres and bypass RLS/grants).

grant usage, select on sequence public.checkin_attempts_id_seq to anon;
grant usage, select on sequence public.audit_log_id_seq to anon;

grant execute on function
  public.point_in_polygon(double precision, double precision, jsonb),
  public.haversine_meters(double precision, double precision, double precision, double precision),
  public.point_in_event_geofence(uuid, double precision, double precision),
  public.record_pin_attempt(uuid, text, text),
  public.claim_device_for_event(uuid, text, text),
  public.claim_face_match(uuid, text),
  public.report_member_location(uuid, text, double precision, double precision),
  public.auto_checkout_expired_events(),
  public.create_checkin_event(
    text, text, text, text, text, text,
    timestamptz, timestamptz, int, int,
    text[], text[],
    text, double precision, double precision, int, jsonb,
    text, text, text, text
  ),
  public.reset_event_pin(uuid, text),
  public.submit_checkin(
    uuid, text, text, text, text, text,
    double precision, double precision, text,
    text, text
  ),
  public.is_super_admin(text)
  to anon;

-- ════════════════════════════════════════════════════════════════════════════
--  Done. Verify with:
--    select table_name from information_schema.tables where table_schema='public';
--    select routine_name from information_schema.routines where routine_schema='public';
-- ════════════════════════════════════════════════════════════════════════════
